### PR TITLE
PdfResponse: Add strict type support.

### PR DESCRIPTION
**Pull request by janbarasek**
Add strict type support like Nette and PHP 7.1.

### CODE REVIEW

**Comment by janbarasek** [comment]
Btw, in test https://github.com/Joseki/PdfResponse/blob/master/tests/PdfResponse/PdfResponse.page.format.phpt is bug: https://travis-ci.org/Joseki/PdfResponse/jobs/592428751

**Comment by petrparolek** [comment]
@janbarasek  is it ready to merge this PR?

**Comment by janbarasek** [comment]
@petrparolek Yes, I think it's ready to merge.

**Comment by petrparolek** [comment]
https://travis-ci.org/Joseki/PdfResponse/jobs/592428751 test fails

**Comment by petrparolek** [comment]
thanks

**Pull request merged**
