### PR TITLE
Support for nette 3.0 and php 7.3

### PR DESCRIPTION
**Pull request by Stopka**
Upgraded mpdf to version 8
Upgraded to nette 3.0 and fixed incompatibilities
Dropped php 5.6 and 7.0 support (due to nette 3.0 incompatibilities)
Added support for php 7.3
Added method argument and result data types
Transformed to PSR-4 autoloading
Updated tests

### CODE REVIEW

**Comment by castamir** [comment]
Thanks, gonna take a look

**Comment by castamir** [comment]
@Stopka could you please take a look on failing CI build please?

**Comment by Stopka** [comment]
Could you try to restart the test? It seems to me like a one time error in mPDF. On my forked branch it always passes all tests: https://travis-ci.org/Stopka/PdfResponse

**Comment by castamir** [comment]
released v5.0.0 with your change... report any bugs you find, if any... 
thanks for contributing

**Pull request merged**
