### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by matrixinfologics**
updated "mpdf/mpdf": "7.*"

I am getting this error(https://prnt.sc/hv3ghm) in my project.

### CODE REVIEW

**Comment by castamir** [comment]
I see, mpdf v7 has many breaking changes...

**Comment by castamir** [comment]
see #21

**Comment by matrixinfologics** [comment]
Thanks 

When I am trying to install it on php 7.0 and nette framework 2.4 then some files are missing from vendor/mpdf/mpdf folder and getting below error.
https://prnt.sc/hvwcu7

**Comment by castamir** [comment]
Could you create repro steps to show what cause this error, plese? I cannot fix it just by looking on your error message...

Try to create a minimalistic app with this error and for example put in on github or just write down a list of steps after which this error occures...

**Comment by matrixinfologics** [comment]
Below is my composer.json file of nette framework. After that I run command `composer update joseki/pdf-response`. 

> `{

	"name": "amati/admin",
	"description": "Administration system for Amati the online auction house",
	"keywords": ["nette"],
	"type": "project",
	"license": ["proprietary"],
	"require": {
		"php": ">= 7.0",
		"nette/application": "^2.4",
		"nette/bootstrap": "^2.4.2",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"dg/composer-cleaner": "^1.1",
		"nextras/orm": "^2.2",
		"nextras/dbal": "^2.1",
		"kdyby/console": "^2.6",
		"nextras/migrations": "^3.0",
		"klimesf/mailgun": "^0.1.0",
		"ublaboo/datagrid": "^5.2",
		"nextras/forms": "^2.0",
		"kdyby/translation": "^2.4",
		"joseki/pdf-response": "dev-master"
	},	
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/Joseki/PdfResponse/"
		}
	],
	"require-dev": {
		"nette/tester": "^1.7"
	},
	"minimum-stability": "stable"
}
`
Output of command is https://prnt.sc/hvyd6c.

When I am trying to create pdf using `$pdf = new \Joseki\Application\Responses\PdfResponse($template);` then get error https://prnt.sc/hvwcu7

Please help me to find out the solution.

**Pull request closed without merging**
